DE-278 | ANALYZE TABLE Functionality
neighborhoods/honeycomb pull request #64
Opened 2021-05-11 20:13 UTC by Geoiv

### Added
- Functionality to perform `ANALYZE TABLE` commands, including on partitions
and on columns. This can be used to increase query performance on specific tables

### Changed
- Added convenience syntax to `add_partition` for providing schema and
table name in the same argument (was missing previously)
- Moved functionality for getting secrets from SSM (AWS parameter store)
from the Salesforce module to its own module

2021-05-11 21:02 UTC, jbarno requested changes
this is neat! Lots of good data will come from analysis.py!

One nitpick/double check on what is arguably a bug by design in python.

2021-05-11 21:08 UTC, Geoiv commented on honeycomb/analysis.py
> +def analyze_columns(table_name, schema=None, columns=[]):
Ah, that is an interesting point! I have not encountered this specific side effect, but having had other default argument issues with Python, I actually think I know exactly what you're talking about here. I agree that I don't think I'd have any problems here, but I will change it just as a matter of good practice. To be honest, I felt weird when I put a list/dict as a default arg, but I brushed it off, should have paid closer attention to that feeling

2021-05-11 21:27 UTC, jbarno approved these changes
👍

2021-05-12 14:24 UTC, frankiezeager approved these changes
Looks great!

2021-05-12 15:08 UTC, merged